schema_version: 1

context:
  name: sceua
  version: "0.1.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sceua-${{ version }}.tar.gz
  sha256: c5eafe6569747112b1227e7c80521bdcf4b02cbfa9408f5af0ad9225846e1a6f

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2
    - scipy >=1.15

tests:
  - python:
      imports:
        - sceua
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Parameter calibration using Shuffle Complex Evolution algorithm.
  license: MIT
  license_file: LICENSE
  homepage: https://sceua.readthedocs.io/en/latest/
  repository: https://github.com/cheginit/sceua/
  documentation: https://sceua.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cheginit
